services:
  redis:
    image: redis:alpine
    container_name: imageflow_redis
    command: redis-server --requirepass redis_pass
    ports:
      - '6379:6379'
    restart: always
  db:
    image: postgres:17
    container_name: imageflow_db
    restart: always
    environment:
      POSTGRES_USER: imageflow_user
      POSTGRES_PASSWORD: imageflow_pass
      POSTGRES_DB: imageflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./data/minio:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
